import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { ConfigProvider, Layout } from "antd";
import Header from "@/components/header/header";
import Content from "@/components/content/content";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Genshin Fan",
  description: "Generated by KanThin",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader />
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#00b96b",
              borderRadius: 2,
              colorBgContainer: "#f6ffed",
            },
          }}
        >
          <Layout>
            <Header />
            <div className="height-body">
              <Content>{children}</Content>
            </div>
          </Layout>
        </ConfigProvider>
      </body>
    </html>
  );
}
